# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Хильченко_1700\bohdan_worker\kestinish_hu\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(636, 660)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calendarium = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarium.setGeometry(QtCore.QRect(0, 0, 461, 311))
        self.calendarium.setStyleSheet("font: 11pt \"Arial\";\n"
"")
        self.calendarium.setGridVisible(True)
        self.calendarium.setSelectionMode(QtWidgets.QCalendarWidget.SingleSelection)
        self.calendarium.setNavigationBarVisible(True)
        self.calendarium.setDateEditEnabled(True)
        self.calendarium.setObjectName("calendarium")
        self.widget = QVideoWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 310, 461, 301))
        self.widget.setObjectName("widget")
        self.startbutton = QtWidgets.QPushButton(self.centralwidget)
        self.startbutton.setGeometry(QtCore.QRect(470, 20, 161, 31))
        self.startbutton.setStyleSheet("font: 11pt \"Arial\";")
        self.startbutton.setObjectName("startbutton")
        self.stopbuttton = QtWidgets.QPushButton(self.centralwidget)
        self.stopbuttton.setGeometry(QtCore.QRect(470, 70, 161, 31))
        self.stopbuttton.setStyleSheet("font: 11pt \"Arial\";")
        self.stopbuttton.setObjectName("stopbuttton")
        self.autostart = QtWidgets.QCheckBox(self.centralwidget)
        self.autostart.setGeometry(QtCore.QRect(470, 120, 91, 31))
        self.autostart.setStyleSheet("font: 11pt \"Arial\";")
        self.autostart.setObjectName("autostart")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 636, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startbutton.setText(_translate("MainWindow", "Старт"))
        self.stopbuttton.setText(_translate("MainWindow", "Стоп"))
        self.autostart.setText(_translate("MainWindow", "Автостарт"))
from PyQt5.QtMultimediaWidgets import QVideoWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
