# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Хильченко_1700\bohdan_worker\wise_notes\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 555)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.note_text = QtWidgets.QTextEdit(self.centralwidget)
        self.note_text.setGeometry(QtCore.QRect(3, 0, 561, 511))
        self.note_text.setStyleSheet("border-color: rgb(25, 144, 18);\n"
"background-color: rgb(205, 255, 196);")
        self.note_text.setObjectName("note_text")
        self.note_list = QtWidgets.QListWidget(self.centralwidget)
        self.note_list.setGeometry(QtCore.QRect(570, 20, 221, 161))
        self.note_list.setStyleSheet("border-color: rgb(25, 144, 18);\n"
"background-color: rgb(205, 255, 196);")
        self.note_list.setObjectName("note_list")
        self.note_list_label = QtWidgets.QLabel(self.centralwidget)
        self.note_list_label.setGeometry(QtCore.QRect(570, -15, 81, 41))
        self.note_list_label.setObjectName("note_list_label")
        self.tag_list = QtWidgets.QListWidget(self.centralwidget)
        self.tag_list.setGeometry(QtCore.QRect(570, 260, 221, 181))
        self.tag_list.setStyleSheet("border-color: rgb(25, 144, 18);\n"
"background-color: rgb(205, 255, 196);")
        self.tag_list.setObjectName("tag_list")
        self.note_save = QtWidgets.QPushButton(self.centralwidget)
        self.note_save.setGeometry(QtCore.QRect(570, 212, 221, 21))
        self.note_save.setStyleSheet("background-color: rgb(52, 170, 25);\n"
"border-color: rgb(48, 143, 25);\n"
"border-top-color: rgb(48, 143, 25);\n"
"border-bottom-color: rgb(48, 143, 25);\n"
"border-right-color: rgb(48, 143, 25);\n"
"border-left-color: rgb(48, 143, 25);")
        self.note_save.setObjectName("note_save")
        self.note_create = QtWidgets.QPushButton(self.centralwidget)
        self.note_create.setGeometry(QtCore.QRect(570, 190, 111, 21))
        self.note_create.setStyleSheet("background-color: rgb(52, 170, 25);\n"
"border-color: rgb(48, 143, 25);\n"
"border-top-color: rgb(48, 143, 25);\n"
"border-bottom-color: rgb(48, 143, 25);\n"
"border-right-color: rgb(48, 143, 25);\n"
"border-left-color: rgb(48, 143, 25);")
        self.note_create.setObjectName("note_create")
        self.note_delete = QtWidgets.QPushButton(self.centralwidget)
        self.note_delete.setGeometry(QtCore.QRect(680, 190, 111, 21))
        self.note_delete.setStyleSheet("background-color: rgb(52, 170, 25);\n"
"border-color: rgb(48, 143, 25);\n"
"border-top-color: rgb(48, 143, 25);\n"
"border-bottom-color: rgb(48, 143, 25);\n"
"border-right-color: rgb(48, 143, 25);\n"
"border-left-color: rgb(48, 143, 25);")
        self.note_delete.setObjectName("note_delete")
        self.tag_list_search = QtWidgets.QPushButton(self.centralwidget)
        self.tag_list_search.setGeometry(QtCore.QRect(570, 492, 221, 21))
        self.tag_list_search.setStyleSheet("background-color: rgb(52, 170, 25);\n"
"border-color: rgb(48, 143, 25);\n"
"border-top-color: rgb(48, 143, 25);\n"
"border-bottom-color: rgb(48, 143, 25);\n"
"border-right-color: rgb(48, 143, 25);\n"
"border-left-color: rgb(48, 143, 25);")
        self.tag_list_search.setObjectName("tag_list_search")
        self.tag_list_unpin = QtWidgets.QPushButton(self.centralwidget)
        self.tag_list_unpin.setGeometry(QtCore.QRect(680, 470, 111, 21))
        self.tag_list_unpin.setStyleSheet("font: 7pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(52, 170, 25);\n"
"border-color: rgb(48, 143, 25);\n"
"border-top-color: rgb(48, 143, 25);\n"
"border-bottom-color: rgb(48, 143, 25);\n"
"border-right-color: rgb(48, 143, 25);\n"
"border-left-color: rgb(48, 143, 25);")
        self.tag_list_unpin.setObjectName("tag_list_unpin")
        self.tag_list_add = QtWidgets.QPushButton(self.centralwidget)
        self.tag_list_add.setGeometry(QtCore.QRect(570, 470, 111, 21))
        self.tag_list_add.setStyleSheet("font: 7pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(52, 170, 25);\n"
"border-color: rgb(48, 143, 25);\n"
"border-top-color: rgb(48, 143, 25);\n"
"border-bottom-color: rgb(48, 143, 25);\n"
"border-right-color: rgb(48, 143, 25);\n"
"border-left-color: rgb(48, 143, 25);")
        self.tag_list_add.setObjectName("tag_list_add")
        self.line_edit_tag = QtWidgets.QLineEdit(self.centralwidget)
        self.line_edit_tag.setGeometry(QtCore.QRect(640, 450, 151, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.line_edit_tag.setFont(font)
        self.line_edit_tag.setStyleSheet("border-color: rgb(25, 144, 18);\n"
"background-color: rgb(205, 255, 196);")
        self.line_edit_tag.setInputMask("")
        self.line_edit_tag.setText("")
        self.line_edit_tag.setObjectName("line_edit_tag")
        self.tag_list_label = QtWidgets.QLabel(self.centralwidget)
        self.tag_list_label.setGeometry(QtCore.QRect(570, 230, 81, 31))
        self.tag_list_label.setObjectName("tag_list_label")
        self.line_edit_label = QtWidgets.QLabel(self.centralwidget)
        self.line_edit_label.setGeometry(QtCore.QRect(570, 430, 81, 51))
        self.line_edit_label.setStyleSheet("font: 7.5pt \"MS Shell Dlg 2\" ;\n"
"color: rgb(83, 83, 83);")
        self.line_edit_label.setObjectName("line_edit_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Wise Notes - Розумні Нотатки"))
        self.note_list_label.setText(_translate("MainWindow", "Список Нотаток"))
        self.note_save.setText(_translate("MainWindow", "Зберегти нотатку"))
        self.note_create.setText(_translate("MainWindow", "Створити нотатку"))
        self.note_delete.setText(_translate("MainWindow", "Видалити нотатку"))
        self.tag_list_search.setText(_translate("MainWindow", "Шукати нотатки по тегу"))
        self.tag_list_unpin.setText(_translate("MainWindow", "Відкріпити від нотатки"))
        self.tag_list_add.setText(_translate("MainWindow", "Додати до нотатки"))
        self.tag_list_label.setText(_translate("MainWindow", "Список Тегів"))
        self.line_edit_label.setText(_translate("MainWindow", "Введіть теги..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
